name: deathpro-remake
version: '${version}'

main: org.firestorm.deathproRemake.DeathproRemake
api-version: '1.21'
load: POSTWORLD

softdepend:
  - ProtocolLib
  - ProtocolSupport
  - ViaVersion
  - ViaBackwards
  - ViaRewind
  - Geyser-Spigot